remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Pesto Academy]
description: [Creating economic and personal growth through innovative and inclusive learning experiences.]
header_pages:
  - about.md
  - news.md
  - people.md
  